// <auto-generated />
using System;
using Automantri.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Automantri.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AutomantriDbContext))]
[Migration("20260605051000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

        modelBuilder.Entity("Automantri.Domain.Entities.Car", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<int>("CityMpg")
                .HasColumnType("integer")
                .HasColumnName("city_mpg");

            b.Property<int>("CombinationMpg")
                .HasColumnType("integer")
                .HasColumnName("combination_mpg");

            b.Property<int?>("Cylinders")
                .HasColumnType("integer")
                .HasColumnName("cylinders");

            b.Property<decimal?>("Displacement")
                .HasPrecision(8, 2)
                .HasColumnType("numeric(8,2)")
                .HasColumnName("displacement");

            b.Property<string>("Drive")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("drive");

            b.Property<string>("FuelType")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("fuel_type");

            b.Property<int>("HighwayMpg")
                .HasColumnType("integer")
                .HasColumnName("highway_mpg");

            b.Property<string>("Make")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("character varying(120)")
                .HasColumnName("make");

            b.Property<string>("Model")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("character varying(120)")
                .HasColumnName("model");

            b.Property<DateTimeOffset>("RetrievedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("retrieved_at_utc");

            b.Property<string>("SourceQuery")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("character varying(120)")
                .HasColumnName("source_query");

            b.Property<string>("Transmission")
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("transmission");

            b.Property<string>("VehicleClass")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("character varying(120)")
                .HasColumnName("vehicle_class");

            b.Property<int>("Year")
                .HasColumnType("integer")
                .HasColumnName("year");

            b.HasKey("Id")
                .HasName("pk_cars");

            b.HasIndex("Make", "Model", "Year", "Transmission")
                .HasDatabaseName("ix_cars_make_model_year_transmission");

            b.ToTable("cars", (string)null);
        });
    }
}
