// <auto-generated />
using System;
using Automantri.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Automantri.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AutomantriDbContext))]
    partial class AutomantriDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Automantri.Domain.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CarType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("car_type");

                    b.Property<int>("CityMpg")
                        .HasColumnType("integer")
                        .HasColumnName("city_mpg");

                    b.Property<int>("CombinationMpg")
                        .HasColumnType("integer")
                        .HasColumnName("combination_mpg");

                    b.Property<int?>("Cylinders")
                        .HasColumnType("integer")
                        .HasColumnName("cylinders");

                    b.Property<decimal?>("Displacement")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("displacement");

                    b.Property<string>("Drive")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("drive");

                    b.Property<int?>("EndProductionYear")
                        .HasColumnType("integer")
                        .HasColumnName("end_production_year");

                    b.Property<string>("FuelType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fuel_type");

                    b.Property<string>("Generation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("generation");

                    b.Property<int>("HighwayMpg")
                        .HasColumnType("integer")
                        .HasColumnName("highway_mpg");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("image_url");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at_utc");

                    b.Property<string>("Serie")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("serie");

                    b.Property<string>("SourceQuery")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("source_query");

                    b.Property<string>("SpecificationsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("specifications_json");

                    b.Property<int?>("StartProductionYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_production_year");

                    b.Property<string>("Transmission")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transmission");

                    b.Property<string>("Trim")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trim");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VehicleClass")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("vehicle_class");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("Make", "Model", "Year", "Transmission", "Trim")
                        .IsUnique();

                    b.ToTable("cars", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
